title: Bong5's Tech & Daily
subtitle: 업무 / 스터디 / 개인 공부 블로그
description: >- # this means to ignore newlines until "baseurl:"
  update update update my
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

author_logo: profile.png
disqus_shortname: Bong5  #for comments using disqus
author: Bong5
author_bio: Bong5
author_email: "leebongho9204@gmail.com"
author_location: Seoul
author_website_url: "https://yourwebsite.com"

# social links
twitter_username: yourusername
github_username:  BongHoLee
facebook_username: yourusername
linkedin_username: yourusername
behance_username: yourusername
instagram_username: yourusername
medium_username: yourusername
telegram_username: yourusername
dribbble_username: yourusername
flickr_username: yourusername
