title: Bong5's Tech Blog
subtitle: 일상, 기술 블로그
description: >- # this means to ignore newlines until "baseurl:"
Solution Programmer in KCB. like coding, arch, talking about IT tech
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com

author_logo: profile.png
disqus_shortname: Bong_ho  #for comments using disqus
author: Bong5s
author_bio: "Solution Programmer in KCB. like coding, arch, talking about IT tech."
author_email: "leebongho9204@gmail.com"
author_location: Korea
#author_website_url: "https://yourwebsite.com"

# social links
twitter_username: yourusername
github_username:  BongHoLee
facebook_username: bongho.lee
linkedin_username: yourusername
behance_username: yourusername
instagram_username: yourusername
medium_username: yourusername
telegram_username: yourusername
dribbble_username: yourusername
flickr_username: yourusername
